[config]
skip_core_tasks = true

# ------------------------
# HELP
# ------------------------
[tasks.help]
category = "Help"
description = "List all tasks"
command = "cargo"
args = ["make", "--list-all-steps", "--quiet"]

# ------------------------
# Install
# ------------------------
[tasks.install]
description = "Install dependencies"
dependencies = ["install-tailwind"]

[tasks.install-tailwind]
description = "Install tailwindcss"
dependencies = ["download-tailwlind", "chmod-tailwind", "rename-tailwind"]

[tasks.download-tailwlind]
command = "curl"
args = [
  "-sLO",
  "https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-macos-arm64",
]

[tasks.chmod-tailwind]
command = "chmod"
args = ["+x", "tailwindcss-macos-arm64"]

[tasks.rename-tailwind]
command = "mv"
args = ["tailwindcss-macos-arm64", "tailwindcss"]

# ------------------------
# Development
# ------------------------
[tasks.watch]
description = "Watch mode development"
run_task = { name = ["server-watch", "styles-watch"], parallel = true }

[tasks.styles-watch]
description = "Run tailwindcss in watch mode"
command = "./tailwindcss"
args = [
  "--config",
  "tailwind.config.js",
  "--input",
  "static/input.css",
  "--output",
  "static/styles.css",
  "--watch",
]

[tasks.server-watch]
command = "cargo"
env = { RUST_LOG = "trace", RUST_BACKTRACE = "full" }
args = ["watch", "-x", "r"]


# ------------------------
# Build
# ------------------------
[tasks.build]
description = "Build locally"
run_task = { name = ["styles", "server"] }

[tasks.styles]
description = "Build tailwindcss for locally"
command = "./tailwindcss"
args = [
  "--minify",
  "--config",
  "tailwind.config.js",
  "--input",
  "static/input.css",
  "--output",
  "static/styles.css",
]

[tasks.server]
description = "Build the server for release locally"
command = "cargo"
args = ["build", "--release"]

# ------------------------
# Release
# ------------------------
[tasks.release]
description = "Build the application for release (run inside Docker)"
run_task = { name = ["styles", "rm-css", "server-release", "rename-release"] }

[tasks.server-release]
description = "Build the server for alpine (run inside Docker)"
command = "cargo"
args = ["build", "--release"]

[tasks.rename-release]
description = "Rename the release binary (run inside Docker)"
command = "mv"
args = ["./target/release/rolo", "./rolo"]

[tasks.rm-css]
description = "Remove input.css (run inside Docker)"
command = "rm"
args = ["static/input.css"]
