//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "contacts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub version: String,
    pub name: String,
    pub formated_name: String,
    pub birthday: Option<String>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub photo: Option<Vec<u8>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::contact_interactions::Entity")]
    ContactInteractions,
    #[sea_orm(has_many = "super::intervals::Entity")]
    Intervals,
}

impl Related<super::contact_interactions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContactInteractions.def()
    }
}

impl Related<super::intervals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Intervals.def()
    }
}

impl Related<super::interactions::Entity> for Entity {
    fn to() -> RelationDef {
        super::contact_interactions::Relation::Interactions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::contact_interactions::Relation::Contacts.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
