//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "interaction")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub date_time: String,
    pub description: Option<String>,
    pub r#type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::contact_interaction::Entity")]
    ContactInteraction,
}

impl Related<super::contact_interaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContactInteraction.def()
    }
}

impl Related<super::contact::Entity> for Entity {
    fn to() -> RelationDef {
        super::contact_interaction::Relation::Contact.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::contact_interaction::Relation::Interaction
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
