//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::contact_interactions::Entity as ContactInteractions;
pub use super::interactions::Entity as Interactions;
pub use super::intervals::Entity as Intervals;
