//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::contact::Entity as Contact;
pub use super::contact_interaction::Entity as ContactInteraction;
pub use super::interaction::Entity as Interaction;
pub use super::interval::Entity as Interval;
